vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /assets/images/produits/
            upload_destination: '%kernel.project_dir%/public/assets/images/produits/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
